# Generated by Django 4.2.15 on 2024-09-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_technology_techinproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinproject',
            name='tech_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.technology'),
        ),
    ]
