# Generated by Django 4.2.15 on 2024-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_techinproject_tech_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tag', models.CharField(max_length=30)),
                ('imageData', models.ImageField(default=None, upload_to='project_images/')),
            ],
        ),
    ]
