# Generated by Django 4.2.15 on 2024-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_origin',
            field=models.CharField(default='', max_length=30),
        ),
    ]
