# Generated by Django 4.2.15 on 2024-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_images_image_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
